### ISSUE TITLE
Python3.9 compat

### ISSUE THREAD

**Issue by freesoul** [ip2location/ip2proxy-python-c#1]
1. the strings in the sample have to be passed as bytes 
such as 
```
record = db.get_all(b"1.0.4.1")
```
2. there is a problem in the CDLL module, which is not direclty influenced by this package, but basically you need to modify the __init__.py of CDLL in line 364 so that
```
if '/' in name or '\\' in name:
```
becomes
```
if name and ('/' in name or '\\' in name):
```
I know it is not your library, but maybe you can find a workaround meanwhile. 

3. I was turning crazy trying to figure out why everything is "-" in the results. I thought the IP2Proxy contained also the geolocation data in addition to the proxy info. I dont know if it is mentioned somewhere in the readme

**Comment by ip2location-com** [comment]
Hi [freesoul](https://github.com/freesoul),

1. We had made some fixes for the bytes issue. You can download the files and test again. Thank you for reporting that. 
2. At this moment it is not affecting us but we will take a note on that. Thank you for mentioning this.
3. IP2Proxy database will only contain the information for Proxy IP addresses. You can see the value of `is_proxy`, if it is 0, the IP address is not a proxy, hence no other information will be returned. If you required geolocation data for non-proxy IP address as well, perhaps you may also need to use IP2Location BIN database and [IP2Location-Python-C](https://github.com/ip2location/ip2location-python-c) as well.
